### ISSUE TITLE
TypeError: Failed to execute 'fetch' on 'Window': Request cannot be constructed from a URL that includes credentials: ../rpc transmission

### ISSUE THREAD

**Issue by 7obias** [johman10/flood-for-transmission#319] opened 2021-12-21 18:28 UTC
setup on a synology transmission I get 

TypeError: Failed to execute 'fetch' on 'Window': Request cannot be constructed from a URL that includes credentials: ../rpc transmission

gui shows but no status.
thx.

**Comment by johman10** [comment] 2021-12-22 08:09
Which browser are you using?

**Comment by johman10** [comment] 2021-12-24 11:53
If you go to a url in the format of: `http://username:password@example.com/`.

Then please remove the username:password part from the URL and log in with the prompt you're given. If you do it that way it should work as expected.

I'm closing this issue since I'm unable to reproduce without more information but feel free to let me know if you need more support.

**Closed by johman10** 2021-12-24 11:53 UTC

**Comment by 7obias** [comment] 2021-12-24 13:35
thanks. I do realize that I was opening the web ui from a chrome plugin that was adding the credentials from the plugin to the opened url. this was causing the problem issue.  Thanks @johman10  for the help. happy holidays.
